version: '3.8'

services:
  # Pythonで動くWebアプリケーションサーバー
  app:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      # ブラウザから http://localhost:8080 でアクセスできるようにする
      - "8080:8001"
    volumes:
      # ローカルのpython-serverディレクトリをコンテナの/appに同期する
      # これにより、コードを修正した際に自動でリロードがかかる
      - ./python-server:/app
    command: ["uvicorn", "processing:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]